### ISSUE TITLE
Unable to send mail，self signed certificate

### ISSUE THREAD

**Issue by einsqing** [nodemailer/smtp-server#115]
`{ Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1048:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:628:8) code: 'ESOCKET', command: 'CONN' }`

**Comment by ryan20090101** [comment]
Do you have tls enabled in your server?

**Comment by ryan20090101** [comment]
Try in nodemailer
    tls:{rejectUnauthorized:false}
